outputChatBox("3c")
addEvent("requestSpawnVehicle", true)
addEventHandler("requestSpawnVehicle", resourceRoot, MarkerSpawnVeh) 
addEventHandler("onMarkerHit", resourceRoot, clientCreateGUI)
--addEventHandler("onMarkerHit", resourceRoot, MarkerSpawnVeh)         
addEventHandler("onMarkerHit", resourceRoot, destroyMarker)
addCommandHandler("pos", ShowElementCurrentRotation)
addCommandHandler ( "gui", clientCreateGUI )
